FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-runtime
MAINTAINER old-wang <old-wang@gmail.com>

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

# 安装ssh，用于远程debug（在本地运行服务器上的的python解释器，需借助ssh）
# 实际工作中，本地环境一般不具备各种gpu硬件资源，无法运行gpu方面的程序。此时必须借助远程debug。
RUN apt-get update --fix-missing && apt-get install --fix-missing -y openssh-server
RUN mkdir -p /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

COPY . /data/app
WORKDIR /data/app
ENV LANG C.UTF-8
EXPOSE 8000

CMD cd /data/app/ && python tests/unit_tests/env/run_unit_tests.py
