# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: segment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='segment.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rsegment.proto\"W\n\nSegRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x18\n\x10\x65nable_stop_word\x18\x03 \x01(\x08\x12\x0f\n\x07use_ner\x18\x04 \x01(\x08\"m\n\x0bSegResponse\x12 \n\x05terms\x18\x01 \x03(\x0b\x32\x11.SegResponse.Term\x1a<\n\x04Term\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x13\n\x0bstart_index\x18\x02 \x01(\x05\x12\x11\n\tend_index\x18\x03 \x01(\x05\"z\n\x0bPosResponse\x12 \n\x05terms\x18\x01 \x03(\x0b\x32\x11.PosResponse.Term\x1aI\n\x04Term\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x13\n\x0bstart_index\x18\x02 \x01(\x05\x12\x11\n\tend_index\x18\x03 \x01(\x05\x12\x0b\n\x03pos\x18\x04 \x01(\t\"\x16\n\x04\x42ool\x12\x0e\n\x06status\x18\x01 \x01(\x08\"9\n\x0e\x41\x64\x64WordRequest\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0b\n\x03pos\x18\x02 \x01(\t\x12\x0c\n\x04\x66req\x18\x03 \x01(\x05\"!\n\x11\x44\x65leteWordRequest\x12\x0c\n\x04word\x18\x01 \x01(\t2\xa3\x01\n\x07Segment\x12\"\n\x03seg\x12\x0b.SegRequest\x1a\x0c.SegResponse\"\x00\x12\"\n\x03pos\x12\x0b.SegRequest\x1a\x0c.PosResponse\"\x00\x12$\n\x08\x61\x64\x64_word\x12\x0f.AddWordRequest\x1a\x05.Bool\"\x00\x12*\n\x0b\x64\x65lete_word\x12\x12.DeleteWordRequest\x1a\x05.Bool\"\x00\x62\x06proto3'
)




_SEGREQUEST = _descriptor.Descriptor(
  name='SegRequest',
  full_name='SegRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='SegRequest.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='SegRequest.model', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_stop_word', full_name='SegRequest.enable_stop_word', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_ner', full_name='SegRequest.use_ner', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=104,
)


_SEGRESPONSE_TERM = _descriptor.Descriptor(
  name='Term',
  full_name='SegResponse.Term',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='SegResponse.Term.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_index', full_name='SegResponse.Term.start_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_index', full_name='SegResponse.Term.end_index', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=215,
)

_SEGRESPONSE = _descriptor.Descriptor(
  name='SegResponse',
  full_name='SegResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='terms', full_name='SegResponse.terms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SEGRESPONSE_TERM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=215,
)


_POSRESPONSE_TERM = _descriptor.Descriptor(
  name='Term',
  full_name='PosResponse.Term',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='PosResponse.Term.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_index', full_name='PosResponse.Term.start_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_index', full_name='PosResponse.Term.end_index', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos', full_name='PosResponse.Term.pos', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=339,
)

_POSRESPONSE = _descriptor.Descriptor(
  name='PosResponse',
  full_name='PosResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='terms', full_name='PosResponse.terms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_POSRESPONSE_TERM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=339,
)


_BOOL = _descriptor.Descriptor(
  name='Bool',
  full_name='Bool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Bool.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=363,
)


_ADDWORDREQUEST = _descriptor.Descriptor(
  name='AddWordRequest',
  full_name='AddWordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='AddWordRequest.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos', full_name='AddWordRequest.pos', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='freq', full_name='AddWordRequest.freq', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=422,
)


_DELETEWORDREQUEST = _descriptor.Descriptor(
  name='DeleteWordRequest',
  full_name='DeleteWordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='DeleteWordRequest.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=457,
)

_SEGRESPONSE_TERM.containing_type = _SEGRESPONSE
_SEGRESPONSE.fields_by_name['terms'].message_type = _SEGRESPONSE_TERM
_POSRESPONSE_TERM.containing_type = _POSRESPONSE
_POSRESPONSE.fields_by_name['terms'].message_type = _POSRESPONSE_TERM
DESCRIPTOR.message_types_by_name['SegRequest'] = _SEGREQUEST
DESCRIPTOR.message_types_by_name['SegResponse'] = _SEGRESPONSE
DESCRIPTOR.message_types_by_name['PosResponse'] = _POSRESPONSE
DESCRIPTOR.message_types_by_name['Bool'] = _BOOL
DESCRIPTOR.message_types_by_name['AddWordRequest'] = _ADDWORDREQUEST
DESCRIPTOR.message_types_by_name['DeleteWordRequest'] = _DELETEWORDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SegRequest = _reflection.GeneratedProtocolMessageType('SegRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEGREQUEST,
  '__module__' : 'segment_pb2'
  # @@protoc_insertion_point(class_scope:SegRequest)
  })
_sym_db.RegisterMessage(SegRequest)

SegResponse = _reflection.GeneratedProtocolMessageType('SegResponse', (_message.Message,), {

  'Term' : _reflection.GeneratedProtocolMessageType('Term', (_message.Message,), {
    'DESCRIPTOR' : _SEGRESPONSE_TERM,
    '__module__' : 'segment_pb2'
    # @@protoc_insertion_point(class_scope:SegResponse.Term)
    })
  ,
  'DESCRIPTOR' : _SEGRESPONSE,
  '__module__' : 'segment_pb2'
  # @@protoc_insertion_point(class_scope:SegResponse)
  })
_sym_db.RegisterMessage(SegResponse)
_sym_db.RegisterMessage(SegResponse.Term)

PosResponse = _reflection.GeneratedProtocolMessageType('PosResponse', (_message.Message,), {

  'Term' : _reflection.GeneratedProtocolMessageType('Term', (_message.Message,), {
    'DESCRIPTOR' : _POSRESPONSE_TERM,
    '__module__' : 'segment_pb2'
    # @@protoc_insertion_point(class_scope:PosResponse.Term)
    })
  ,
  'DESCRIPTOR' : _POSRESPONSE,
  '__module__' : 'segment_pb2'
  # @@protoc_insertion_point(class_scope:PosResponse)
  })
_sym_db.RegisterMessage(PosResponse)
_sym_db.RegisterMessage(PosResponse.Term)

Bool = _reflection.GeneratedProtocolMessageType('Bool', (_message.Message,), {
  'DESCRIPTOR' : _BOOL,
  '__module__' : 'segment_pb2'
  # @@protoc_insertion_point(class_scope:Bool)
  })
_sym_db.RegisterMessage(Bool)

AddWordRequest = _reflection.GeneratedProtocolMessageType('AddWordRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDWORDREQUEST,
  '__module__' : 'segment_pb2'
  # @@protoc_insertion_point(class_scope:AddWordRequest)
  })
_sym_db.RegisterMessage(AddWordRequest)

DeleteWordRequest = _reflection.GeneratedProtocolMessageType('DeleteWordRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEWORDREQUEST,
  '__module__' : 'segment_pb2'
  # @@protoc_insertion_point(class_scope:DeleteWordRequest)
  })
_sym_db.RegisterMessage(DeleteWordRequest)



_SEGMENT = _descriptor.ServiceDescriptor(
  name='Segment',
  full_name='Segment',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=460,
  serialized_end=623,
  methods=[
  _descriptor.MethodDescriptor(
    name='seg',
    full_name='Segment.seg',
    index=0,
    containing_service=None,
    input_type=_SEGREQUEST,
    output_type=_SEGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='pos',
    full_name='Segment.pos',
    index=1,
    containing_service=None,
    input_type=_SEGREQUEST,
    output_type=_POSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='add_word',
    full_name='Segment.add_word',
    index=2,
    containing_service=None,
    input_type=_ADDWORDREQUEST,
    output_type=_BOOL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete_word',
    full_name='Segment.delete_word',
    index=3,
    containing_service=None,
    input_type=_DELETEWORDREQUEST,
    output_type=_BOOL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEGMENT)

DESCRIPTOR.services_by_name['Segment'] = _SEGMENT

# @@protoc_insertion_point(module_scope)
